version: '2'
services:

  # The Application
  app:
    container_name: app
    build:
      context: ./
      dockerfile: app.dockerfile
    networks:
    - backend
    working_dir: /var/www
    volumes:
      - ./app:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  # The Web Server
  web:
    container_name: apache
    depends_on:
      - app
      - database
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    # volumes:
      # - ./app:/var/www
    volumes_from:
      - app
    ports:
      - 8080:8080
      - 9000:9000
    networks:
      - frontend
      - backend

  # The Database
  database:
    container_name: mysql
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
    ports:
        - "33061:3306"

volumes:
  dbdata:

networks:
  frontend:
  backend: